name: CI

on:
  push:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use node
        uses: actions/setup-node@v2
        with:
         node_version: 12

      - name: Install deps
        run: npm install

      - name: Run lint
        run: npm run lint